# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.h2.Driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  #user: sa
  user: root
  # the password
  password: root

  # the JDBC URL
  #url: jdbc:h2:mem:test
  url: jdbc:mysql://localhost:3306/coding_challenge

server : 
 type: simple
 rootPath: /expenses-manager/*
 applicationContextPath: /